apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: backend-latency-staging
  namespace: staging
spec:
  action: delay
  mode: one
  selector:
    namespaces: [staging]
    labelSelectors:
      app: helioops
      component: backend
  delay:
    latency: "200ms"
    correlation: "25"
    jitter: "50ms"
  duration: "10m"
  scheduler:
    cron: "@every 168h"